// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcxfwtkrwvfbnugcwkcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjeGZ3dGtyd3ZmYm51Z2N3a2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTY4NTEsImV4cCI6MjA2NTI3Mjg1MX0.ri1fA2iDInQLbvPY-gOC5QohbXNugIoVhkF8IyVdNjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);